# Generated by Django 3.2.7 on 2021-09-27 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_auto_20210927_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likeed',
            new_name='liked',
        ),
    ]
